name: Build and push image to Docker Hub

on:
    push:
        branches:
            - master

jobs:
    build-and-push-image-to-docker-hub:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Set up Buildx
              uses: docker/setup-buildx-action@v3
            
            - name: Authenticate to Docker Hub
              uses: docker/login-action@v3
              with:
                registry: docker.io
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PAT }}
            
            - name: Build and push image to Docker hub
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/chat-room:latest