name: Docker scout CVE scan

on:
  pull_request:
    branches: 
      - master
jobs:
    scan-docker-image-for-vulnerabilities:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Buildx
              uses: docker/setup-buildx-action@v3
      
            - name: Authenticate to Docker hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PAT }}

            - name: Build Docker image
              uses: docker/build-push-action@v6
              with:
                context: .
                file: ./Dockerfile
                sbom: true # Enable SBOM
                push: false

            - name: Check for CVEs on Docker scout
              uses: docker/scout-action@v1
              with:
                command: cves
                image: chat-room:latest
                ignore-unchanged: true
                only-severities: critical,high

            - name: Provide recommendations
              uses: docker/scout-action@v1
              with:
                command: recommendations